orion7_denuncia_homepage:
    pattern:  /
    defaults: { _controller: Orion7CoreBundle:Denuncia:index }
    requirements:
        _method:  GET

test_admin:
    pattern:  /admin
    defaults: { _controller: Orion7CoreBundle:Denuncia:index }
    requirements:
        _method:  GET