Orion7CoreBundle_denuncia_homepage:
    pattern:  /
    defaults: { _controller: Orion7CoreBundle:Denuncia:index }
    requirements:
        _method:  GET

Orion7CoreBundle_denuncia_new:
    pattern:  /denuncia
    defaults: { _controller: Orion7CoreBundle:Denuncia:new }
    requirements:
        _method:  GET

Orion7CoreBundle_incidente_listbycentro:
    pattern:  /incidentes/centro/{codCentro}
    defaults: { _controller: Orion7CoreBundle:Incidente:listByCentro }
    requirements:
        _method:  GET
        codCentro: \d+

Orion7CoreBundle_incidente_show:
    pattern:  /incidente/{id}
    defaults: { _controller: Orion7CoreBundle:Incidente:show }
    requirements:
        _method:  GET
        id: \d+

Orion7CoreBundle_canalizaciones:
    pattern:  /canalizaciones/{idIncidente}
    defaults: { _controller: Orion7CoreBundle:Canalizacion:index }
    requirements:
        _method:  GET
        idIncidente: \d+

Orion7CoreBundle_estado_list:
    pattern:  /estados
    defaults: { _controller: Orion7CoreBundle:Estado:index }
    requirements:
        _method:  GET

Orion7CoreBundle_municipio_listbyestado:
    pattern:  /municipios/{estado}
    defaults: { _controller: Orion7CoreBundle:Municipio:listByEstado }
    requirements:
        _method:  GET
        estado: \d+

Orion7CoreBundle_parroquia_listbymunicipio:
    pattern:  /parroquias/{municipio}
    defaults: { _controller: Orion7CoreBundle:Parroquia:listByMunicipio }
    requirements:
        _method:  GET
        municipio: \d+

Orion7CoreBundle_centro_listbyparroquia:
    pattern:  /centros/{parroquia}
    defaults: { _controller: Orion7CoreBundle:Centro:listByParroquia }
    requirements:
        _method:  GET
        parroquia: \d+

test_admin:
    pattern:  /admin
    defaults: { _controller: Orion7CoreBundle:Denuncia:index }
    requirements:
        _method:  GET

Orion7CoreBundle_selects_municipio:
    pattern:  /select_municipio
    defaults: { _controller: Orion7CoreBundle:Municipio:selectByEstado }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_parroquia:
    pattern:  /select_parroquia
    defaults: { _controller: Orion7CoreBundle:Parroquia:selectByMunicipio }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_centro:
    pattern:  /select_centro
    defaults: { _controller: Orion7CoreBundle:Centro:selectByParroquia }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_subcategoria:
    pattern:  /select_subcategoria
    defaults: { _controller: Orion7CoreBundle:Subcategoria:selectByCategoria }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_codigo_centro:
    pattern:  /select_codigo_centro
    defaults: { _controller: Orion7CoreBundle:Centro:selectByCodigoCentro }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_cedula_elector:
    pattern:  /select_cedula_elector
    defaults: { _controller: Orion7CoreBundle:Centro:selectByCedulaElector }
    requirements:
        _method:  GET|POST

Orion7CoreBundle_selects_incidentes:
    pattern:  /select_incidentes
    defaults: { _controller: Orion7CoreBundle:Incidente:buscarIncidentes }
    requirements:
        _method:  GET|POST