<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121207234203 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE canalizacion ADD usuario INT DEFAULT NULL");
        $this->addSql("ALTER TABLE canalizacion ADD CONSTRAINT FK_800ECFA62265B05D FOREIGN KEY (usuario) REFERENCES usuario (id)");
        $this->addSql("CREATE INDEX IDX_800ECFA62265B05D ON canalizacion (usuario)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE canalizacion DROP FOREIGN KEY FK_800ECFA62265B05D");
        $this->addSql("DROP INDEX IDX_800ECFA62265B05D ON canalizacion");
        $this->addSql("ALTER TABLE canalizacion DROP usuario");
    }
}
