<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121209144201 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE denuncia CHANGE hora_hecho hora_hecho DATETIME NOT NULL, CHANGE hora_registro hora_registro DATETIME NOT NULL");
        $this->addSql("ALTER TABLE canalizacion CHANGE hora_registro hora_registro DATETIME NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE canalizacion CHANGE hora_registro hora_registro DATE NOT NULL");
        $this->addSql("ALTER TABLE denuncia CHANGE hora_hecho hora_hecho DATE NOT NULL, CHANGE hora_registro hora_registro DATE NOT NULL");
    }
}
