<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121202211113 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE elector (cedula INT NOT NULL, centro INT DEFAULT NULL, letra_cedula VARCHAR(1) NOT NULL, primer_apellido VARCHAR(35) NOT NULL, segundo_apellido VARCHAR(35) NOT NULL, primer_nombre VARCHAR(35) NOT NULL, segundo_nombre VARCHAR(35) NOT NULL, fecha_nacimiento DATE NOT NULL, estado INT NOT NULL, municipio INT NOT NULL, parroquia INT NOT NULL, INDEX IDX_4C0374392675036B (centro), PRIMARY KEY(cedula)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE elector ADD CONSTRAINT FK_4C0374392675036B FOREIGN KEY (centro) REFERENCES centro (codigo)");
        $this->addSql("ALTER TABLE centro CHANGE electores num_electores INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE elector");
        $this->addSql("ALTER TABLE centro CHANGE num_electores electores INT NOT NULL");
    }
}
