<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121204005544 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE canalizacion (id INT AUTO_INCREMENT NOT NULL, incidente INT DEFAULT NULL, comentario LONGTEXT NOT NULL, hora_registro DATE NOT NULL, INDEX IDX_800ECFA612858081 (incidente), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE canalizacion ADD CONSTRAINT FK_800ECFA612858081 FOREIGN KEY (incidente) REFERENCES incidente (id)");
        $this->addSql("ALTER TABLE incidente ADD resuelto TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE canalizacion");
        $this->addSql("ALTER TABLE incidente DROP resuelto");
    }
}
