<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121215222249 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE mensaje (id INT AUTO_INCREMENT NOT NULL, usuario INT DEFAULT NULL, texto LONGTEXT NOT NULL, rolDestinado VARCHAR(100) NOT NULL, horaCreado DATETIME NOT NULL, INDEX IDX_9B631D012265B05D (usuario), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D012265B05D FOREIGN KEY (usuario) REFERENCES usuario (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE mensaje");
    }
}
