<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121207213412 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE denuncia ADD usuario_registro INT DEFAULT NULL, ADD usuario_filtrado INT DEFAULT NULL");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_F4236796D1BD5AC2 FOREIGN KEY (usuario_registro) REFERENCES usuario (id)");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_F4236796A2921FBE FOREIGN KEY (usuario_filtrado) REFERENCES usuario (id)");
        $this->addSql("CREATE INDEX IDX_F4236796D1BD5AC2 ON denuncia (usuario_registro)");
        $this->addSql("CREATE INDEX IDX_F4236796A2921FBE ON denuncia (usuario_filtrado)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE denuncia DROP FOREIGN KEY FK_F4236796D1BD5AC2");
        $this->addSql("ALTER TABLE denuncia DROP FOREIGN KEY FK_F4236796A2921FBE");
        $this->addSql("DROP INDEX IDX_F4236796D1BD5AC2 ON denuncia");
        $this->addSql("DROP INDEX IDX_F4236796A2921FBE ON denuncia");
        $this->addSql("ALTER TABLE denuncia DROP usuario_registro, DROP usuario_filtrado");
    }
}
