<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121125235001 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE responsable (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE responsables_denuncias (responsable INT NOT NULL, denuncia INT NOT NULL, INDEX IDX_37A5951052520D07 (responsable), INDEX IDX_37A59510F4236796 (denuncia), PRIMARY KEY(responsable, denuncia)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE articulo (id INT AUTO_INCREMENT NOT NULL, ley INT DEFAULT NULL, numero INT NOT NULL, contenido LONGTEXT NOT NULL, INDEX IDX_69E94E918FDFBD2C (ley), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE articulos_subcategorias (articulo INT NOT NULL, subcategoria INT NOT NULL, INDEX IDX_1ADC5B4169E94E91 (articulo), INDEX IDX_1ADC5B41DA7FB914 (subcategoria), PRIMARY KEY(articulo, subcategoria)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE denuncia (id INT AUTO_INCREMENT NOT NULL, incidente INT DEFAULT NULL, via INT DEFAULT NULL, tipo_denunciante INT DEFAULT NULL, hora_hecho DATE NOT NULL, hora_registro DATE NOT NULL, relato LONGTEXT NOT NULL, nombre_denunciante VARCHAR(100) NOT NULL, telefonos_denunciante VARCHAR(100) NOT NULL, correo_denunciante VARCHAR(100) NOT NULL, twitter_denunciante VARCHAR(100) NOT NULL, genera_retraso TINYINT(1) NOT NULL, INDEX IDX_F423679612858081 (incidente), INDEX IDX_F423679621B74CD0 (via), INDEX IDX_F42367968FE27041 (tipo_denunciante), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE categoria (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, descripcion LONGTEXT NOT NULL, categoria_ushahidi INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ente (id INT AUTO_INCREMENT NOT NULL, tipo_ente INT DEFAULT NULL, estado INT DEFAULT NULL, municipio INT DEFAULT NULL, telefono VARCHAR(100) NOT NULL, INDEX IDX_197E17221351C067 (tipo_ente), INDEX IDX_197E1722265DE1E3 (estado), INDEX IDX_197E1722FE98F5E0 (municipio), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE usuario (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, nombre VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_2265B05D92FC23A8 (username_canonical), UNIQUE INDEX UNIQ_2265B05DA0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE centro (codigo INT NOT NULL, estado INT DEFAULT NULL, municipio INT DEFAULT NULL, parroquia INT DEFAULT NULL, codigo_municipio INT NOT NULL, codigo_parroquia INT NOT NULL, nombre VARCHAR(255) NOT NULL, direccion LONGTEXT NOT NULL, electores INT NOT NULL, mesas INT NOT NULL, nuevo TINYINT(1) NOT NULL, latitud DOUBLE PRECISION NOT NULL, longitud DOUBLE PRECISION NOT NULL, INDEX IDX_2675036B265DE1E3 (estado), INDEX IDX_2675036BFE98F5E0 (municipio), INDEX IDX_2675036B23A71668 (parroquia), PRIMARY KEY(codigo)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_ente (id INT AUTO_INCREMENT NOT NULL, tipo VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_denunciante (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, es_publico TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE incidente (id INT AUTO_INCREMENT NOT NULL, estado INT DEFAULT NULL, municipio INT DEFAULT NULL, parroquia INT DEFAULT NULL, centro INT DEFAULT NULL, INDEX IDX_12858081265DE1E3 (estado), INDEX IDX_12858081FE98F5E0 (municipio), INDEX IDX_1285808123A71668 (parroquia), INDEX IDX_128580812675036B (centro), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE subcategoria (id INT AUTO_INCREMENT NOT NULL, categoria INT DEFAULT NULL, nombre VARCHAR(100) NOT NULL, descripcion LONGTEXT NOT NULL, asistencia LONGTEXT NOT NULL, categoria_ushahidi INT NOT NULL, INDEX IDX_DA7FB9144E10122D (categoria), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE subcategorias_denuncias (subcategoria INT NOT NULL, denuncia INT NOT NULL, INDEX IDX_74CCE702DA7FB914 (subcategoria), INDEX IDX_74CCE702F4236796 (denuncia), PRIMARY KEY(subcategoria, denuncia)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE municipio (id INT AUTO_INCREMENT NOT NULL, estado INT DEFAULT NULL, codigo INT NOT NULL, nombre VARCHAR(100) NOT NULL, latitud DOUBLE PRECISION NOT NULL, longitud DOUBLE PRECISION NOT NULL, INDEX IDX_FE98F5E0265DE1E3 (estado), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE via (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE estado (codigo INT NOT NULL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY(codigo)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE parroquia (id INT AUTO_INCREMENT NOT NULL, estado INT DEFAULT NULL, municipio INT DEFAULT NULL, codigo INT NOT NULL, nombre VARCHAR(100) NOT NULL, latitud DOUBLE PRECISION NOT NULL, longitud DOUBLE PRECISION NOT NULL, INDEX IDX_23A71668265DE1E3 (estado), INDEX IDX_23A71668FE98F5E0 (municipio), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ley (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, descripcion LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE responsables_denuncias ADD CONSTRAINT FK_37A5951052520D07 FOREIGN KEY (responsable) REFERENCES responsable (id)");
        $this->addSql("ALTER TABLE responsables_denuncias ADD CONSTRAINT FK_37A59510F4236796 FOREIGN KEY (denuncia) REFERENCES denuncia (id)");
        $this->addSql("ALTER TABLE articulo ADD CONSTRAINT FK_69E94E918FDFBD2C FOREIGN KEY (ley) REFERENCES ley (id)");
        $this->addSql("ALTER TABLE articulos_subcategorias ADD CONSTRAINT FK_1ADC5B4169E94E91 FOREIGN KEY (articulo) REFERENCES articulo (id)");
        $this->addSql("ALTER TABLE articulos_subcategorias ADD CONSTRAINT FK_1ADC5B41DA7FB914 FOREIGN KEY (subcategoria) REFERENCES subcategoria (id)");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_F423679612858081 FOREIGN KEY (incidente) REFERENCES incidente (id)");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_F423679621B74CD0 FOREIGN KEY (via) REFERENCES via (id)");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_F42367968FE27041 FOREIGN KEY (tipo_denunciante) REFERENCES tipo_denunciante (id)");
        $this->addSql("ALTER TABLE ente ADD CONSTRAINT FK_197E17221351C067 FOREIGN KEY (tipo_ente) REFERENCES tipo_ente (id)");
        $this->addSql("ALTER TABLE ente ADD CONSTRAINT FK_197E1722265DE1E3 FOREIGN KEY (estado) REFERENCES estado (codigo)");
        $this->addSql("ALTER TABLE ente ADD CONSTRAINT FK_197E1722FE98F5E0 FOREIGN KEY (municipio) REFERENCES municipio (id)");
        $this->addSql("ALTER TABLE centro ADD CONSTRAINT FK_2675036B265DE1E3 FOREIGN KEY (estado) REFERENCES estado (codigo)");
        $this->addSql("ALTER TABLE centro ADD CONSTRAINT FK_2675036BFE98F5E0 FOREIGN KEY (municipio) REFERENCES municipio (id)");
        $this->addSql("ALTER TABLE centro ADD CONSTRAINT FK_2675036B23A71668 FOREIGN KEY (parroquia) REFERENCES parroquia (id)");
        $this->addSql("ALTER TABLE incidente ADD CONSTRAINT FK_12858081265DE1E3 FOREIGN KEY (estado) REFERENCES estado (codigo)");
        $this->addSql("ALTER TABLE incidente ADD CONSTRAINT FK_12858081FE98F5E0 FOREIGN KEY (municipio) REFERENCES municipio (id)");
        $this->addSql("ALTER TABLE incidente ADD CONSTRAINT FK_1285808123A71668 FOREIGN KEY (parroquia) REFERENCES parroquia (id)");
        $this->addSql("ALTER TABLE incidente ADD CONSTRAINT FK_128580812675036B FOREIGN KEY (centro) REFERENCES centro (codigo)");
        $this->addSql("ALTER TABLE subcategoria ADD CONSTRAINT FK_DA7FB9144E10122D FOREIGN KEY (categoria) REFERENCES categoria (id)");
        $this->addSql("ALTER TABLE subcategorias_denuncias ADD CONSTRAINT FK_74CCE702DA7FB914 FOREIGN KEY (subcategoria) REFERENCES subcategoria (id)");
        $this->addSql("ALTER TABLE subcategorias_denuncias ADD CONSTRAINT FK_74CCE702F4236796 FOREIGN KEY (denuncia) REFERENCES denuncia (id)");
        $this->addSql("ALTER TABLE municipio ADD CONSTRAINT FK_FE98F5E0265DE1E3 FOREIGN KEY (estado) REFERENCES estado (codigo)");
        $this->addSql("ALTER TABLE parroquia ADD CONSTRAINT FK_23A71668265DE1E3 FOREIGN KEY (estado) REFERENCES estado (codigo)");
        $this->addSql("ALTER TABLE parroquia ADD CONSTRAINT FK_23A71668FE98F5E0 FOREIGN KEY (municipio) REFERENCES municipio (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE responsables_denuncias DROP FOREIGN KEY FK_37A5951052520D07");
        $this->addSql("ALTER TABLE articulos_subcategorias DROP FOREIGN KEY FK_1ADC5B4169E94E91");
        $this->addSql("ALTER TABLE responsables_denuncias DROP FOREIGN KEY FK_37A59510F4236796");
        $this->addSql("ALTER TABLE subcategorias_denuncias DROP FOREIGN KEY FK_74CCE702F4236796");
        $this->addSql("ALTER TABLE subcategoria DROP FOREIGN KEY FK_DA7FB9144E10122D");
        $this->addSql("ALTER TABLE incidente DROP FOREIGN KEY FK_128580812675036B");
        $this->addSql("ALTER TABLE ente DROP FOREIGN KEY FK_197E17221351C067");
        $this->addSql("ALTER TABLE denuncia DROP FOREIGN KEY FK_F42367968FE27041");
        $this->addSql("ALTER TABLE denuncia DROP FOREIGN KEY FK_F423679612858081");
        $this->addSql("ALTER TABLE articulos_subcategorias DROP FOREIGN KEY FK_1ADC5B41DA7FB914");
        $this->addSql("ALTER TABLE subcategorias_denuncias DROP FOREIGN KEY FK_74CCE702DA7FB914");
        $this->addSql("ALTER TABLE ente DROP FOREIGN KEY FK_197E1722FE98F5E0");
        $this->addSql("ALTER TABLE centro DROP FOREIGN KEY FK_2675036BFE98F5E0");
        $this->addSql("ALTER TABLE incidente DROP FOREIGN KEY FK_12858081FE98F5E0");
        $this->addSql("ALTER TABLE parroquia DROP FOREIGN KEY FK_23A71668FE98F5E0");
        $this->addSql("ALTER TABLE denuncia DROP FOREIGN KEY FK_F423679621B74CD0");
        $this->addSql("ALTER TABLE ente DROP FOREIGN KEY FK_197E1722265DE1E3");
        $this->addSql("ALTER TABLE centro DROP FOREIGN KEY FK_2675036B265DE1E3");
        $this->addSql("ALTER TABLE incidente DROP FOREIGN KEY FK_12858081265DE1E3");
        $this->addSql("ALTER TABLE municipio DROP FOREIGN KEY FK_FE98F5E0265DE1E3");
        $this->addSql("ALTER TABLE parroquia DROP FOREIGN KEY FK_23A71668265DE1E3");
        $this->addSql("ALTER TABLE centro DROP FOREIGN KEY FK_2675036B23A71668");
        $this->addSql("ALTER TABLE incidente DROP FOREIGN KEY FK_1285808123A71668");
        $this->addSql("ALTER TABLE articulo DROP FOREIGN KEY FK_69E94E918FDFBD2C");
        $this->addSql("DROP TABLE responsable");
        $this->addSql("DROP TABLE responsables_denuncias");
        $this->addSql("DROP TABLE articulo");
        $this->addSql("DROP TABLE articulos_subcategorias");
        $this->addSql("DROP TABLE denuncia");
        $this->addSql("DROP TABLE categoria");
        $this->addSql("DROP TABLE ente");
        $this->addSql("DROP TABLE usuario");
        $this->addSql("DROP TABLE centro");
        $this->addSql("DROP TABLE tipo_ente");
        $this->addSql("DROP TABLE tipo_denunciante");
        $this->addSql("DROP TABLE incidente");
        $this->addSql("DROP TABLE subcategoria");
        $this->addSql("DROP TABLE subcategorias_denuncias");
        $this->addSql("DROP TABLE municipio");
        $this->addSql("DROP TABLE via");
        $this->addSql("DROP TABLE estado");
        $this->addSql("DROP TABLE parroquia");
        $this->addSql("DROP TABLE ley");
    }
}
