Orion7\CoreBundle\Entity\Categoria:
    type: entity
    table: categoria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 100
        descripcion:
            type: text
        categoria_ushahidi:
            type: integer
    oneToMany:
        subcategorias:
          targetEntity: Subcategoria
          mappedBy: categoria