Orion7\CoreBundle\Entity\Denuncia:
    type: entity
    table: denuncia
    repositoryClass: Orion7\CoreBundle\Entity\DenunciaRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        hora_hecho:
            type: datetime
        hora_registro:
            type: datetime
        relato:
            type: text
        nombre_denunciante:
            type: string
            length: 100
        telefono_denunciante:
            type: string
            length: 100
        correo_denunciante:
            type: string
            length: 100
        twitter_denunciante:
            type: string
            length: 100
        genera_retraso:
            type: boolean
        isFiltrado:
            type: boolean
        autorizacion_cne:
            type: boolean
        id_ushahidi:
            type: integer
            nullable: true
    manyToOne:
        incidente:
            targetEntity: Incidente
            inversedBy: denuncias
            joinColumn:
                name: incidente
                referencedColumnName: id
        via:
            targetEntity: Via
            inversedBy: denuncias
            joinColumn:
                name: via
                referencedColumnName: id
        tipo_denunciante:
            targetEntity: TipoDenunciante
            inversedBy: denuncias
            joinColumn:
                name: tipo_denunciante
                referencedColumnName: id
        usuario_registro:
            targetEntity: Usuario
            joinColumn:
                name: usuario_registro
                referencedColumnName: id
        usuario_filtrado:
            targetEntity: Usuario
            joinColumn:
                name: usuario_filtrado
                referencedColumnName: id
    manyToMany:
        responsables:
              targetEntity: Responsable
              mappedBy: denuncias
        subcategorias:
              targetEntity: Subcategoria
              mappedBy: denuncias