Orion7\CoreBundle\Entity\Ente:
    type: entity
    table: ente
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        telefono:
            type: string
            length: 100
    manyToOne:
        tipo_ente:
            targetEntity: TipoEnte
            inversedBy: entes
            joinColumn:
                name: tipo_ente
                referencedColumnName: id
        estado:
            targetEntity: Estado
            inversedBy: entes
            joinColumn:
                name: estado
                referencedColumnName: codigo
        municipio:
            targetEntity: Municipio
            inversedBy: entes
            joinColumn:
                name: municipio
                referencedColumnName: id
    manyToMany:
        incidentes:
          targetEntity: Incidente
          inversedBy: entes
          joinTable:
            name: entes_incidentes.
            joinColumns:
              ente:
                referencedColumnName: id
            inverseJoinColumns:
              incidente:
                referencedColumnName: id