Orion7\CoreBundle\Entity\Incidente:
    type: entity
    table: incidente
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        resuelto:
            type: boolean
    oneToMany:
        denuncias:
          targetEntity: Denuncia
          mappedBy: incidente
        canalizaciones:
          targetEntity: Canalizacion
          mappedBy: incidente
    manyToOne:
        estado:
            targetEntity: Estado
            inversedBy: incidentes
            joinColumn:
                name: estado
                referencedColumnName: codigo
        municipio:
            targetEntity: Municipio
            inversedBy: incidentes
            joinColumn:
                name: municipio
                referencedColumnName: id
        parroquia:
            targetEntity: Parroquia
            inversedBy: incidentes
            nullable: true
            joinColumn:
                name: parroquia
                referencedColumnName: id
        centro:
            targetEntity: Centro
            inversedBy: incidentes
            nullable: true
            joinColumn:
                name: centro
                referencedColumnName: codigo
