Orion7\CoreBundle\Entity\TipoDenunciante:
    type: entity
    table: tipo_denunciante
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 50
        es_publico:
            type: boolean
    oneToMany:
        denuncias:
          targetEntity: Denuncia
          mappedBy: tipo_denunciante