Orion7\CoreBundle\Entity\Tipo_ente:
    type: entity
    table: tipo_ente
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        tipo:
            type: string
            length: 100
    oneToMany:
        entes:
          targetEntity: Ente
          mappedBy: tipo_ente