Orion7\CoreBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 100