Orion7\CoreBundle\Entity\Via:
    type: entity
    table: via
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 100
    oneToMany:
        denuncias:
          targetEntity: Denuncia
          mappedBy: via