<?php

namespace Orion7\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends EntityRepository
{
	public function findByEstado($codEstado)
    {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->where('m.estado = :estado')
                   ->setParameter('estado', $codEstado);

        return $qb->getQuery()
                  ->getResult();
    }
}